Modules/Transisi/Routes/web.php
<?php

// use App\Http\Controllers\HomeController;

use Illuminate\Support\Facades\Route;
use Modules\Transisi\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('transisi')->group(function() {
    Route::get('/', [DashboardController::class, 'index'])->middleware('auth');
    Route::resource('company', CompanyController::class)->middleware('auth');
    Route::resource('employee', EmployeeController::class)->middleware('auth');
    Route::get('ajax-pagination',array('as'=>'pagination','uses'=>'CompanyController@ajaxPagination'));
    // Route::get('/company/employeepdf/{id}', [CompanyController::class, 'GetEmployeePDF'])->middleware('auth');
    Route::get('/company/employee_pdf/{id}', 'CompanyController@EmployeePDF');
});

Modules/Transisi/Http/Controllers/DashboardController.php
<?php

namespace Modules\Transisi\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Renderable
     */
    public function index()
    {
        return view('transisi::index');
    }

    /**
     * Show the form for creating a new resource.
     * @return Renderable
     */
    public function create()
    {
        return view('transisi::create');
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Renderable
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function show($id)
    {
        return view('transisi::show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Renderable
     */
    public function edit($id)
    {
        return view('transisi::edit');
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Renderable
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Renderable
     */
    public function destroy($id)
    {
        //
    }
}

Modules/Transisi/Resources/views/dashboard/company-edit.blade.php
@extends('transisi::layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" >
                    {{ $title }}
                </div>

                <div class="card-body">
                    <form action="/transisi/company/{{ $company->id }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
                            <input type="text" class="form-control" name="name" value="{{ $company->name }}">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
                            <input type="text" class="form-control" name="email" value="{{ $company->email }}">
                        </div>
                        <img src="{{ asset('storage/company/' . $company->logo) }}" alt="" width="100px" height="100px">
                        <input type="text" value="{{ $company->logo }}" name="logoOld" hidden>
                        <div class="input-group mb-3">
                            <label class="input-group-text" for="inputGroupFile01">Logo</label>
                            <input type="file" class="form-control" id="logo" name="logoUpload">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Website</span>
                            <input type="text" class="form-control" name="website" value="{{ $company->website }}">
                        </div>
                        <div align="right">
                            <button type="submit" class="btn btn-secondary btn-sm">Edit</button>
                            <a href="{{ url("/transisi/company") }}">
                                <button type="button" class="btn btn-secondary btn-sm">Batal</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Transisi/Resources/views/dashboard/company-insert.blade.php
@extends('transisi::layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" >{{ $title }}</div>

                <div class="card-body">
                    <form action="/transisi/company" method="POST" enctype="multipart/form-data">
                    @csrf
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
                            <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                        </div>
                        <div class="input-group mb-3">
                            <label class="input-group-text" for="inputGroupFile01">Logo</label>
                            <input type="file" class="form-control" id="logo" name="logoUpload" value="{{ old('logo_upload') }}">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Website</span>
                            <input type="text" class="form-control" name="website" value="{{ old('website') }}">
                        </div>
                        <div align="right">
                            <button type="submit" class="btn btn-secondary btn-sm">Tambah</button>
                            <a href="{{ url("/transisi/company") }}">
                                <button type="button" class="btn btn-secondary btn-sm">Batal</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Transisi/Resources/views/dashboard/company.blade.php
@extends('transisi::layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ $title }}</div>
                        <div class="card-body">
                            <a class="btn btn-primary mb-3" href="{{ route('company.create') }}" role="button">Add Company</a>
                            <form action="/transisi/company">
                                <div class="input-group mb-1">
                                    <input type="text" class="form-control" placeholder="Search.." name="search">
                                    <button class="btn btn-outline-dark" type="submit">Search</button>
                                </div>
                            </form>
                            <div id="company">
                                @include('transisi::ajax.company-ajax')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @push('script')
    <script type="text/javascript" src="{{ asset('js/company.js') }}"></script>
    @endpush
@endsection

Modules/Transisi/Resources/views/dashboard/employee-edit.blade.php
@extends('transisi::layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" >{{ $title }}</div>

                <div class="card-body">
                    <form action="/transisi/employee/{{ $employee->id }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
                            <input type="text" class="form-control" name="name" value="{{ $employee->name }}">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
                            <input type="text" class="form-control" name="email" value="{{ $employee->email }}">
                        </div>
                        <div class="input-group mb-3">
                            <label class="input-group-text" for="inputGroupSelect01" style="width: 15%">Options</label>
                            <select class="form-select" id="company" style="width:85%" name="company">
                                @foreach ($company as $data_company)
                                    <option {{ ($employee->company_id == $data_company->id) ? "selected":'' }} value="{{ $data_company->id }}">{{ $data_company->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div align="right">
                            <button type="submit" class="btn btn-secondary btn-sm">Edit</button>
                            <a href="{{ route('employee.index') }}">
                                <button type="button" class="btn btn-secondary btn-sm">Batal</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Transisi/Resources/views/dashboard/employee-insert.blade.php
@extends('transisi::layouts.app')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header" >{{ $title }}</div>

                <div class="card-body">
                    <form action="/transisi/employee" method="POST" enctype="multipart/form-data">
                    @csrf
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Name</span>
                            <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text" id="inputGroup-sizing-default">Email</span>
                            <input type="text" class="form-control" name="email" value="{{ old('email') }}">
                        </div>
                        <div class="input-group mb-3">
                            <label class="input-group-text" for="inputGroupSelect01" style="width: 15%">Options</label>
                            <select class="form-select" id="company" style="width:85%" name="company">
                                @foreach ($company as $data_company)
                                    <option value="{{ $data_company->id }}">{{ $data_company->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div align="right">
                            <button type="submit" class="btn btn-secondary btn-sm">Tambah</button>
                            <a href="{{ url("/transisi/employee") }}">
                                <button type="button" class="btn btn-secondary btn-sm">Batal</button>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

Modules/Transisi/Resources/views/dashboard/employee.blade.php
@extends('transisi::layouts.app')

@section('content')
    <h1 align="center" class="mb-5">Employee</h1>
    <a href="{{ route('employee.create') }}">
        <button type="button" class="btn btn-primary mb-2">Add Employee</button>
    </a>
    <form action="/transisi/employee">
        <div class="input-group mb-1">
            <input type="text" class="form-control" placeholder="Search.." name="search">
            <button class="btn btn-outline-dark" type="submit">Search</button>
        </div>
    </form>
    <div id="employee">
        @include('transisi::ajax.employee-ajax')
    </div>
    @push('script')
    <script type="text/javascript" src="{{ asset('js/employee.js') }}"></script>
    @endpush
@endsection

Modules/Transisi/Resources/views/dashboard/index.blade.php
@extends('layout.navbar')

@section('container')
    @auth
        <h1>Welcome back, {{ auth()->user()->name }}</h1>
    @endauth

    @foreach ($company as $item)
        {{ $item["name"] }}
        
    @endforeach
@endsection